### ISSUE TITLE
Fatal Error when running update: Argument 1 passed to PhpParser\NodeTraverser::addVisitor() must implement interface PhpParser\NodeVisitor

### ISSUE THREAD

**Issue by Romain** [FriendsOfPHP/Sami#253]
Hi,
I'm trying to update the doc of a project using SAMI, and I get the following error:

> PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpParser\NodeTraverser::addVisitor() must implement interface PhpParser\NodeVisitor, instance of Sami\Parser\NodeVisitor given, called in phar:/path/to/sami.phar/Sami/Sami.php on line 110 and defined in phar:/path/to/sami.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:32
> Stack trace:
> #0 phar:/path/to/sami.phar/Sami/Sami.php(110): PhpParser\NodeTraverser->addVisitor(Object(Sami\Parser\NodeVisitor))
> #1 phar:/path/to/sami.phar/vendor/pimple/pimple/src/Pimple/Container.php(113): Sami\Sami->Sami\{closure}(Object(Sami\Sami))
> #2 phar:/path/to/sami.phar/Sami/Sami.php(116): Pimple\Container->offsetGet('php_traverser')
> #3 phar:/path/to/sami.phar/vendor/pimple/pimple/src/Pimple/Container.php(113): Sami\Sami->Sami\{clo in phar:/path/to/sami.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php on line 32

Here is the config file:

```php
<?php

include 'vendor/autoload.php';

use Sami\Sami;
use Symfony\Component\Finder\Finder;

$iterator = Finder::create()
    ->files()
    ->name('*.php')
    ->in($dir = 'src')
;

return new Sami($iterator, array(
    'title'                => 'PHP-FFMpeg API',
    'theme'                => 'enhanced',
    'build_dir'            => __DIR__.'/docs/source/API/API',
    'cache_dir'            => __DIR__.'/docs/source/API/API/cache',
    'default_opened_level' => 2,
));
```

Any idea of what could be wrong?
Thanks for your help.

**Comment by aik099** [comment]
1. what version of Sami are you using
2. provide minimal PHP file, that reproduces the problem
3. what PHP version are you using

?

**Comment by Romain** [comment]
Thanks for your feedback @aik099,

1. I just got the last one using `curl -O http://get.sensiolabs.org/sami.phar`.
3. PHP version is 7.0.11
2. Here is a test file I created in src/test/test.php. I changed the config file accordingly.

```php
<?php

namespace test;

class test
{
    private $ffprobe;

    public function __construct()
    {

    }

    /**
     * Sets FFProbe.
     *
     * @param FFProbe
     *
     * @return FFMpeg
     */
    public function setFFProbe(FFProbe $ffprobe)
    {
        $this->ffprobe = $ffprobe;

        return $this;
    }

    /**
     * Gets FFProbe.
     *
     * @return FFProbe
     */
    public function getFFProbe()
    {
        return $this->ffprobe;
    }
}
```

**Comment by aik099** [comment]
I guess this is side effect from upgrading to new PHP-Parser version.

**Comment by Romain** [comment]
Is there something I could do?

**Comment by aik099** [comment]
You check if for that PHP file documentation generation wasn't causing any errors in other Sami versions. I bet in 1.4 version it worked. I guess this issue is related to #252 and #251 because they all seem to be caused by PHP-Parser upgrade.

**Comment by Romain** [comment]
Thanks @aik099.
Indeed, it seems that some tests fail with the master branch.
Do you have any idea how I could get the phar version of Sami for v1.4? I looked at the branch and the doc, but everything refers to http://get.sensiolabs.org/sami.phar which is the current version.

**Comment by aik099** [comment]
What we totally miss is minimal documentation generation as part of build process. Without this we can't really catch such type of issues unless somebody really stumbles upon them. I was thinking about such type of improvement for a while now, but had no time to implement it.

**Comment by Romain** [comment]
Ok, so for now, I can't really use v1.4?
I just have to wait for a fix to be pushed to master, is that correct?

**Comment by aik099** [comment]
If you only want phar, then yes. You can alternatively install Sami as local/global composer dependency and use that to generate docs. If you're using Sami previously and it worked, then get version of Sami that worked for you and use it.

In any case you can do some investigation and figure out more specific cause for reported issue, then just PHP-Parser version upgrade.

**Comment by aik099** [comment]
I'm unable to reproduce this locally. Here is my setup:

1. PHP 5.5 or PHP 7.0
2. used Sami code from `master` branch
3. removed `{{ block('search_index') }}` from `/Sami/Resources/themes/default/search.twig` (or otherwise I will get an exception)
4. try to generate documentation

**Comment by Romain** [comment]
Hi @aik099,
I'll try to use it as a composer depedency and let you know.
R
